title: Pixel Badge ESP32 LED devboard
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: The main site for Curious Supplies' Pixel Badge ESP32 WiFi-enabled LED devboard
palette: blue
palettes:
  blue:
    sass:
      accent1: '#00c6ff'
      accent2: '#0072ff'
  green:
    sass:
      accent1: '#12db5d'
      accent2: '#11998e'
  navy:
    sass:
      accent1: '#004e92'
      accent2: '#000428'
  violet:
    sass:
      accent1: '#8e2de2'
      accent2: '#4a00e0'
header:
  title: Pixel Badge
#  logo_img: images/logo.svg
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
      has_subnav: false
    - label: Docs
      url: /docs
      style: link
      has_subnav: false
    - label: Blog
      url: /blog
      style: link
      has_subnav: false
#    - label: Tutorials
#      url: /tutorials
#      style: link
#      has_subnav: false
#    - label: Sample Pages
#      url: '#'
#      style: link
#      has_subnav: true
#      subnav_links:
#        - label: Overview
#          url: /overview
#          style: link
#        - label: Showcase
#          url: /showcase
#          style: link
#    - label: Style Guide
#      url: /style-guide
#      style: link
#      has_subnav: false
    - label: Buy
      url: '/#buy'
      style: primary
      has_subnav: false
footer:
  content: 'Curious Supplies by Tom Clement'
  links:
    - label: Made with Stackbit
      url: 'https://www.stackbit.com'
      style: link
      new_window: true
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/Tom_Clement'
      style: icon
      icon_class: fa-twitter
      new_window: true
#    - label: LinkedIn
#      url: 'https://www.linkedin.com/'
#      style: icon
#      icon_class: fa-linkedin
#      new_window: true
    - label: GitHub
      url: 'https://github.com/tjclement'
      style: icon
      icon_class: fa-github
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
